export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const CONFIRM_ORDER_DISH = 'CONFIRM_ORDER_DISH';
export const SHOW_RESUME = 'SHOW_RESUME';
export const ELIMINATE_DISH = 'ELIMINATE_DISH';
export const ORDER_ORDERED = 'ORDER_ORDERED';
